steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '-t', 
    'asia-northeast1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:latest', 
    '--cache-from',
    'asia-northeast1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:latest', 
    '-f',
    'Dockerfile',
    '--build-arg',
    'PORT=8080',
    '.'
    ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'asia-northeast1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:latest', 
    ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 
    'deploy', 
    '--project',
    '$_PROJECT_ID',
    '$_SERVICE_NAME', 
    '--image', 
    'asia-northeast1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:latest', 
    '--region', 
    'asia-northeast1', 
    '--platform', 
    'managed', 
    '--max-instances',
    '100',
    '--min-instances',
    '0',
    '--memory',
    '256Mi',
    '--timeout',
    '1m',
    '--cpu',
    '1',
    '--concurrency',
    '40',
    '--port',
    '8080',
    '--allow-unauthenticated',
    '--ingress',
    'all',
#    '--vpc-connector',
#    '$_VPC_CONNECTOR',
    '--vpc-egress',
    'all-traffic',
#    '--update-env-vars',
#    'PROJECT_ID=$PROJECT_ID',
#    '--update-secrets',
#    'JWT_SECRET=JWT_SECRET:latest',
#    '--service-account',
#    'line-connect@$PROJECT_ID.iam.gserviceaccount.com',
    ]
images:
- 'asia-northeast1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/$_SERVICE_NAME:latest'
options:
  logging: CLOUD_LOGGING_ONLY
